### ISSUE TITLE
Error while loading people data: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 640 path $.results[0].dob

### ISSUE THREAD

**Issue by codingpro007** [Husaynhakeem/Poeple-Kotlin#1]
![listing](https://user-images.githubusercontent.com/28718000/45839516-daa45b00-bd14-11e8-881c-5bdbc8eb4dce.PNG)

pliz i need help

**Comment by husaynhakeem** [comment]
It seems there was an issue in the model classes, this issue was fixed in [this commit](https://github.com/husaynhakeem/Poeple-Kotlin/commit/67a38c2978ee4c72fae462ebff1dc3aa253bbc89)
Thanks for reporting it!
